spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        # namespace: ce076c5a-380f-443c-b65a-b40fd2819070
        # 指定集群名称
        # 南京机房
        cluster-name: BJ
        metadata:
          instance: c
          haha: hehe
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: add-bonus
          #RocketMQ,一定要设置group，用其他MQ可留空
          group: binder-group
        my-input:
          destination: stream-my-topic
          group: my-group
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center

server:
  port: 8081
rocketmq:
  name-server: 127.0.0.1:9876
logging:
  level:
    com.alibaba.nacos: error






##Yet Anther Markup Language(.yml/.yaml) ==> JSON的子集
#
##所有环境公用的配置属性
#management:
#  endpoint:
#    health:
#      show-details: ${SOME_ENV}
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#info:
#  app-name: user-center
#  author: damu
#  email: xxx@email
#
#spring:
#  profiles:
#    active: dev
##连字符
#---
## profile=x的专用属性，也就是某个环境下的专用属性
##开发环境
#spring:
#  profiles: dev
#
#---
## profile=y的专用属性，也就是某个环境下的专用属性
##生产环境
#spring:
#  profiles: prod
#server:
#  tomcat:
#    max-threads: 300
#    max-connections: 1000
#
#

